config/routes.rb
Rails.application.routes.draw do

  resources :tracks
    devise_for :users, controllers: {
      registrations: "user_registrations",
      passwords: "user_passwords"
    }

    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

  scope '/(:locale)' do
    resources :companions do
      collection do
        get 'search'
      end
      member do
        get 'transcript'
        get 'start_merge'
        get 'find_duplicates'
      end
    end

    resources :terms do
      member do
        get 'new_session'
        post 'create_session'
      end

      resources :sessions do
        resources :assessments, controller: :kata_assessments
        resources :learners do
          resources :assessments, controller: :kata_learner_assessments do
            collection do
              post 'final_grade'
            end
          end
        end
        member do
          post 'synchronize_users'
          post 'synchronize_group'
          post 'create_schedule'
          post 'update_schedule/:schedule_id', action: 'update_schedule'
          delete 'destroy_schedule/:schedule_id', action: 'destroy_schedule'
          post 'attendance'
          post 'tardy'
          patch :assign_to_course
          get :transcript
          get :name_tags
          get :export
        end
      end
    end

    resources :kata_schedules
    resources :companions

    resources :courses do
      resources :assessments, controller: :course_assessments
    end

    root to: 'core#index'
  end

end

app/models/term.rb
# == Schema Information
#
# Table name: kata_sessions
#
#  id             :integer          not null, primary key
#  program_id     :integer
#  name           :string(255)
#  description    :string(255)
#  schedule_start :datetime
#  schedule_until :datetime
#  created_at     :datetime
#  updated_at     :datetime
#

class Term < ActiveRecord::Base
  self.table_name = 'kata_sessions'

  belongs_to :program

  has_many :sessions, foreign_key: 'kata_session_id'

  scope :term_summary, -> (options) {
    select(:id, :name, :schedule_start)
    .order('schedule_start desc')
    .page(options[:page])
    .per(10)
  }

  scope :paged_with_programs, -> (options) {
    order('schedule_start DESC')
    .includes(:program)
    .page(options[:page])
    .per(25)
  }

  scope :current_term, -> { limit(1).order('schedule_start desc').first }

  def self.to_csv
    attributes = %w{name program description schedule_start schedule_until}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |course|
        csv << attributes.map { |attr| course.send(attr) }
      end
    end
  end

  def to_csv
    CSV.generate(headers: true) do |csv|
      csv << %w{program name description schedule_start schedule_until}
      csv << [self.program.name, self.name, self.description, self.schedule_start,
        self.schedule_until]
      csv << []
      csv << %w{class_name course_number}
      self.sessions.each do |session|
        csv << [session.name, session.try(:course).try(:number)]
      end
    end
  end
end

app/controllers/terms_controller.rb

class TermsController < TbusBaseController
  before_action :set_term, only: [:show, :edit, :update, :destroy]

  # GET /terms
  # GET /terms.json
  def index
    @terms = Term.paged_with_programs(page: params[:page] || 1)

    respond_to do |format|
      format.html
      format.csv { send_data Term.includes(:program).to_csv,
        filename: "sessions-#{Date.today}.csv" }
    end
  end

  # GET /terms/new
  def new
    @term = Term.new

    # TODO: Programs will need to be filtered by organization
    @programs = Program.all
  end

  def show
    respond_to do |format|
      format.html
      format.csv { send_data @term.to_csv, filename: "session-#{@term.name}.csv" }
    end
  end

  # GET /terms/1/edit
  def edit
    @term = Term.find(params[:id])

    # TODO: Programs will need to be filtered by organization
    @programs = Program.all
  end

  # POST /terms
  # POST /terms.json
  def create
    parse_schedule_times

    @term = Term.new(term_params)

    respond_to do |format|
      if @term.save
        format.html { redirect_to @term, notice: 'Kata session was successfully created.' }
        format.json { render action: 'show', status: :created, location: @term }
      else
        format.html { render action: 'new' }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /terms/1
  # PATCH/PUT /terms/1.json
  def update
    parse_schedule_times

    respond_to do |format|
      if @term.update(term_params)
        format.html { redirect_to action: :show, id: @term.id, notice: 'Kata session was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1
  # DELETE /terms/1.json
  def destroy
    @term.destroy
    respond_to do |format|
      format.html { redirect_to terms_url }
      format.json { head :no_content }
    end
  end

  def new_session
    @term = Term.find(params[:id])
    # TODO: add program support.
    @available_courses = @current_program.courses

  end

  def create_session
    @term = Term.find(params[:id])

    params[:courses].each do |course_number|
      course = Course.where(number: course_number).first
      # TODO: add fault checking on the course

      Session.where(
        kata_session_id: @term.id,
        course_id: course.id,
        name: course.name
      ).first_or_create
    end

    redirect_to action: 'show', id: @term.id
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_term
      @term = Term.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def term_params
      params.require(:term).permit(:program_id, :name, :description, :schedule_start, :schedule_until)
    end

    def parse_schedule_times
      params[:term][:schedule_start] = Date.strptime params[:term][:schedule_start], '%m/%d/%Y'
      params[:term][:schedule_until] = Date.strptime params[:term][:schedule_until], '%m/%d/%Y'
    end

end

app/views/terms/_current_term.html.haml
%h3= term.name

app/views/terms/_form.html.haml
= form_for @term do |f|
  .form-group
    = f.label :program_id
    = f.select :program_id, options_for_select(@programs.collect { |x| [x.name, x.id] }), {},
      class: 'form-control select2'
  .form-group
    = f.label :name
    = f.text_field :name, type: 'text', class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control', rows: 5
  .form-group
    = f.label :schedule_start
    = f.text_field :schedule_start, class: 'form-control with-datepicker', id: 'schedule_start',
      value: (l(@term.schedule_start.to_date) unless @term.schedule_start.nil?)
  .form-group
    = f.label :schedule_until
    = f.text_field :schedule_until, class: 'form-control with-datepicker', id: 'schedule_until',
        value: (l(@term.schedule_until.to_date) unless @term.schedule_until.nil?)
  .form-actions
    = f.submit nil, class: 'btn btn-primary'
    = link_to t('.cancel', default: t('helpers.links.cancel')),
      terms_path, class: 'btn btn-secondary'

app/views/terms/_term_summary.html.haml
- unless local_assigns.key? :terms
  .alert.alert-warning terms is undefined

- else
  - model_class = Term

  .card.card-block
    .card-title
      %h4.pull-left #{@current_program.name} - Terms
      %h5.pull-right
        = link_to terms_path(format: :csv) do
          = fa_icon 'share-square-o'
        = link_to new_term_path do
          = fa_icon 'plus'
    %table.table
      %thead
        %tr
          %th= model_class.human_attribute_name(:name)
          %th= model_class.human_attribute_name(:schedule_start)
      %tbody
        - terms.each do |term|
          %tr
            %td= link_to term.name, term_path(term.id)
            %td= l term.schedule_start.to_date, format: :long
    .pager= paginate terms

app/views/terms/edit.html.haml
- content_for(:page_heading, "#{@current_program.name} - Edit #{@term.name}")

.row
  .col-sm-6
    .card
      .card-block
        = render partial: 'form'

app/views/terms/index.html.haml
:ruby
  model_class = Term
  content_for :page_heading, 'ALI Terms'

.container-fluid
  .row
    .col-sm-12
      .card.card-block
        .card-title
          %h4.pull-left
          %h5.pull-right
            = link_to terms_path(format: 'csv') do
              = fa_icon 'share-square-o'
            = link_to new_term_path do
              = fa_icon 'plus'
        %table.table.table-striped
          %thead
            %tr
              %th= model_class.human_attribute_name(:name)
              %th= model_class.human_attribute_name(:program)
              %th= model_class.human_attribute_name(:description)
              %th= model_class.human_attribute_name(:schedule_start)
              %th= model_class.human_attribute_name(:schedule_until)
              %th= t '.actions', default: t("helpers.actions")
          %tbody
            - @terms.each do |kata_session|
              %tr
                %td= link_to kata_session.name, term_path(kata_session.id)
                %td= kata_session.program.name
                %td= kata_session.description
                %td= l(kata_session.schedule_start.to_date, format: :long) unless kata_session.schedule_start.nil?
                %td= l(kata_session.schedule_until.to_date, format: :long) unless kata_session.schedule_until.nil?
                %td

                  = link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_term_path(kata_session.id), class: 'btn btn-sm btn-primary'
                  = link_to t('.destroy', :default => t("helpers.links.destroy")),
                    term_path(kata_session), method: :delete,
                    data: { confirm: t('.confirm', default: t("helpers.links.confirm",
                            default: 'Are you sure?')) }, class: 'btn btn-sm btn-danger'
        .pager= paginate @terms

app/views/terms/new.html.haml
- content_for :page_heading, "#{@current_program.name} - New Term"

.row
  .col-sm-6
    .card
      .card-block
        = render partial: 'form'

app/views/terms/new_session.html.haml
:ruby
  content_for :page_heading, "Abundant Life Institute - #{@term.name}"

.container-fluid
  .row
    .col-sm-6
      .card.card-block
        .card-title
          %h5 Available Courses
        = form_tag "/terms/#{@term.id}/create_session" do
          %table.table.table-striped
            %thead
              %tr
                %th
                %th Number
                %th Name
            %tbody
              - @available_courses.each do |course|
                %tr
                  %td= check_box_tag 'courses[]', course.number
                  %td= course.number
                  %td= course.name
          %tfoot
            %tr
              %td{colspan: 3}= submit_tag 'Add Courses', class: 'btn btn-primary'

app/views/terms/show.html.haml
:ruby
  model_class = Term
  content_for :page_heading, "#{@current_program.name} - #{@term.name}"

.container-fluid
  .row
    .col-sm-6
      .card.card-block
        .card-title
          %h5.pull-right
            = link_to term_path(id: @term.id, format: :csv), title: 'Export' do
              = fa_icon 'share-square-o'
            = link_to edit_term_path(@term), title: 'Edit' do
              = fa_icon 'pencil', class: 'text-warning'
            = link_to(term_path(@term), method: 'delete',
              data: { confirm: t('.confirm') }, title: 'Delete') do
              = fa_icon 'trash', class: 'text-danger'
        %dl
          %dt= model_class.human_attribute_name(:program_id)
          %dd= @term.program.name
          %dt= model_class.human_attribute_name(:name)
          %dd= @term.name
          %dt= model_class.human_attribute_name(:description)
          %dd= @term.description
          %dt= model_class.human_attribute_name(:schedule_start)
          %dd= l @term.schedule_start.to_date, format: :long
          %dt= model_class.human_attribute_name(:schedule_until)
          %dd= l(@term.schedule_until.to_date, format: :long) unless @term.schedule_until.nil?

    .col-sm-6
      .card.card-block
        .card-title
          %h5.pull-right
            = link_to new_session_term_path(@term), title: 'Add Course' do
              = fa_icon 'plus'
        %table.table.table-striped
          %thead
            %tr
              %th= t('session.name')
              %th= t('course.number')
              %th= 'Synced?'
          %tbody
            - @term.sessions.each do |session|
              %tr
                %td= link_to session.name, term_session_path(@term, session)
                %td= session.try(:course).try(:number)
                %td= session.external_id.nil? ? fa_icon('chain-broken', class: 'text-danger') : |
                  fa_icon('link', class: 'text-success') |