config/routes.rb
Rails.application.routes.draw do

  resources :tracks
    devise_for :users, controllers: {
      registrations: "user_registrations",
      passwords: "user_passwords"
    }

    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

  scope '/(:locale)' do
    resources :companions do
      collection do
        get 'search'
      end
      member do
        get 'transcript'
        get 'start_merge'
        get 'find_duplicates'
      end
    end

    resources :terms do
      member do
        get 'new_session'
        post 'create_session'
      end

      resources :sessions do
        resources :assessments, controller: :kata_assessments
        resources :learners do
          resources :assessments, controller: :kata_learner_assessments do
            collection do
              post 'final_grade'
            end
          end
        end
        member do
          post 'synchronize_users'
          post 'synchronize_group'
          post 'create_schedule'
          post 'update_schedule/:schedule_id', action: 'update_schedule'
          delete 'destroy_schedule/:schedule_id', action: 'destroy_schedule'
          post 'attendance'
          post 'tardy'
          patch :assign_to_course
          get :transcript
          get :name_tags
          get :export
        end
      end
    end

    resources :kata_schedules
    resources :companions

    resources :courses do
      resources :assessments, controller: :course_assessments
    end

    root to: 'core#index'
  end

end

app/controllers/companions_controller.rb

class CompanionsController < TbusBaseController
  before_filter :initialize_controller

  def index
    @companions = Person.companion_summary(page: params[:page] || 1)
  end

  def show
    @companion = Person.find_with_contact params[:id]
    @student = Student.work_with_tracks @companion.student.id
    @tracks = Track.all
  end

  def new
    @companion = Person.new
  end

  def create
    @companion = Person.new(companion_params)

    respond_to do |format|
      if @companion.save
        format.html { redirect_to companion_path(@companion.id),
          notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @companion }
      else
        format.html { render action: 'new' }
        format.json { render json: @companion.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    student_service = StudentService.new
    student_service.find_by_person_id params[:id]

    respond_to do |format|
      if student_service.update_student(companion_params)
        format.html { redirect_to companion_path(student_service.student.person.id),
          notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @companion }
      else
        format.html { render action: 'show' }
        format.json { render json: @companion.errors, status: :unprocessable_entity }
      end
    end
  end

  def transcript
    @companion = Person.find_with_contact params[:id]

    transcript = Documents::Transcript.new @companion

    respond_to do |format|
      format.pdf { send_data transcript.render, filename: 'summary_report.pdf',
        type: 'application/pdf', disposition: 'inline' }
    end
  end

  def search
    cev = ContactEntityValue.arel_table
    contact_entity_values = ContactEntityValue.where(cev[:value].matches("%#{params[:search]}%")).includes(:contact)
    contact_values = contact_entity_values.select { |e| e.contact.contactable_type == 'Person' }.map { |e| e.contact_id }
    contacts = Contact.where(id: contact_values)

    @companions = Person.where(id: contacts.map { |e| e.contactable_id })
                        .includes(:roles, contact: [:phones, :names, :addresses])
                        .page(params[:page] || 1).per(20)

    #@companions = Person.joins(:students)
    #People.joins(:city => {:state => :country})
    #.where(:country => {:id => Country.first.id}).all
    render action: :index
  end

  def start_merge
    @companion = Person.find_with_contact params[:id]

    
  end

  private

    def companion_params
      params.require(:person).permit(:last_name, :first_name, :email_address, :address_1,
        :address_2, :city, :state, :postal_code, :external_id)
    end

    def initialize_controller
      Person.send(:include, EnPerson)
    end
end

app/views/companions/_en_companion_details.html.haml
%tr
  %td
    = link_to companion_path companion.id do
      = companion.proper_name.first_name
      = companion.proper_name.last_name
  %td= companion.contact.phones.first.nil? ? '' : companion.contact.phones.first.value
  %td= companion.contact.addresses.select{ |x| x.name == 'Home'}.first.nil? ? '' : companion.contact.addresses.select{ |x| x.name == 'Home'}.first.address_1
  %td= companion.roles.map{ |x| x.type }.join(',')

app/views/companions/_en_form.html.haml
= bootstrap_form_for @companion, label_errors: true, url: form_path,
  html: { class: 'form-horizontal' } do |f|
  = f.alert_message 'Please check the following errors.', error_summary: false
  = f.text_field :first_name
  = f.text_field :last_name
  = f.text_field :email_address
  = f.text_field :address_1
  = f.text_field :address_2
  = f.text_field :city
  = f.text_field :state
  = f.text_field :postal_code
  = f.text_field :external_id
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")),
    companions_path, :class => 'btn btn-secondary'

app/views/companions/index.html.haml
:ruby
  model_class = User
  content_for :page_heading, 'Abundant Life Institute - Companions'

.container-fluid
  .row
    .col-sm-12
      .card.card-block
        .card-title.clearfix
          %h4.pull-left
            Companions
          %span.pull-left
            = form_tag search_companions_path, method: 'GET' do
              = text_field_tag :search, '', class: 'span12', placeholder: 'Search'
          %h5.pull-right
            = link_to new_companion_path, title: 'New Companion' do
              = fa_icon 'plus'
        %table.table
          %thead
            %tr
              %th Name
              %th Phone
              %th Address
              %th Roles
          %tbody
            - @companions.each do |companion|
              = render partial: "#{I18n.locale}_companion_details", locals: { companion: companion }
        .pager= paginate @companions

app/views/companions/new.html.haml
:ruby
  model_class = Course
  content_for :page_heading, "Abundant Life Institute - New Companion"

.row
  .col-sm-6
    .card
      .card-block
        = render :partial => "en_form", locals: { form_path: companions_path }

app/views/companions/show.html.haml
:ruby
  model_class = User
  content_for :page_heading, "Abundant Life Institute -
    #{@companion.proper_name.first_name}
    #{@companion.proper_name.last_name}"

.row
  .col-sm-6
    .card.card-block
      .card-title
        %h4.pull-left User Information
        %h5.pull-right          
          = link_to start_merge_companion_path(id: @companion.id), title: 'Merge', class: 'inactive' do
            = fa_icon 'compress'
      .card-body.clear-all
        = render :partial => "en_form", locals: { form_path: companion_path(@companion) }


  .col-sm-6
    .card.card-block
      .card-title
        %h4.pull-left Track Progress
        %h5.pull-right
      - @student.kata_learners.chunk { |c| c.session.course.track }.each do |track,learners|
        %table.table
          %thead
            %tr
              %th{ width: '60%' }= track.name
              %th
              %th{ witdh: '40%' }= "Completed: #{learners.length}"
          %tbody
            - learners.each do |learner|
              %tr
                %td= "#{show_if_found(learner.session.course, :number)}  -  #{show_if_found(learner.session.course, :name)}"
                %td= learner.session.term.name
                %td= learner.final_assessment

    .card.card-block
      .card-title
        %h4.pull-left Course Work
        %h5.pull-right
          = link_to transcript_companion_path(id: @companion.id, format: :pdf), title: 'Export' do
            = fa_icon 'share-square-o'
      %table.table
        %thead
          %tr
            %th= 'Course'
            %th= 'Track'
            %th= 'Date Taken'
            %th= 'Grade'
        %tbody
          - @companion.try(:student).try(:kata_learners).try(:each) do |learner|
            %tr
              %td= "#{show_if_found(learner.session.course, :number)}  -  #{show_if_found(learner.session.course, :name)}"
              %td= learner.session.course.track.name
              %td= learner.session.term.name
              %td= learner.final_assessment