config/routes.rb
Rails.application.routes.draw do

  resources :tracks
    devise_for :users, controllers: {
      registrations: "user_registrations",
      passwords: "user_passwords"
    }

    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

  scope '/(:locale)' do
    resources :companions do
      collection do
        get 'search'
      end
      member do
        get 'transcript'
        get 'start_merge'
        get 'find_duplicates'
      end
    end

    resources :terms do
      member do
        get 'new_session'
        post 'create_session'
      end

      resources :sessions do
        resources :assessments, controller: :kata_assessments
        resources :learners do
          resources :assessments, controller: :kata_learner_assessments do
            collection do
              post 'final_grade'
            end
          end
        end
        member do
          post 'synchronize_users'
          post 'synchronize_group'
          post 'create_schedule'
          post 'update_schedule/:schedule_id', action: 'update_schedule'
          delete 'destroy_schedule/:schedule_id', action: 'destroy_schedule'
          post 'attendance'
          post 'tardy'
          patch :assign_to_course
          get :transcript
          get :name_tags
          get :export
        end
      end
    end

    resources :kata_schedules
    resources :companions

    resources :courses do
      resources :assessments, controller: :course_assessments
    end

    root to: 'core#index'
  end

end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id              :integer          not null, primary key
#  course_type_id  :integer
#  grading_type_id :integer
#  name            :string(255)
#  number          :string(255)
#  description     :string(255)
#  level           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class Course < ActiveRecord::Base
  belongs_to :course_type
  belongs_to :grading_type
  belongs_to :track
  
  has_many :assessment_types, through: :course_assessments
  has_many :assessments, class_name: 'CourseAssessment'
  has_many :course_catalogs
  has_many :programs, through: :course_catalogs

  validates :name, uniqueness: true, length: { in: 1..254 }
  validates :number, uniqueness: true, length: { in: 1..254 }

  enum status: [:archived, :active, :upcoming]

  def to_csv
    CSV.generate do |csv|
      csv << %w{name number description created_at}
      csv << [self.name, self.number, self.description, self.created_at]
      csv << []
      csv << %w{assessment_name type potential}
      self.assessments.each do |assessment|
        csv << [assessment.name, assessment.assessment_type.name, assessment.potential]
      end
    end
  end

  def self.all_to_csv
    attributes = %w{name number description created_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |course|
        csv << attributes.map { |attr| course.send(attr) }
      end
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < TbusBaseController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index

    @courses = Course.all.order('name asc')

    respond_to do |format|
      format.html
      format.csv { send_data @courses.all_to_csv, filename: "courses-#{Date.today}.csv" }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    respond_to do |format|
      format.html
      format.csv { send_data @course.to_csv, filename: "course-#{@course.number}.csv" }
    end
  end

  # GET /courses/new
  def new
    @course = Course.new
    @tracks = Track.all

    # Currently we'll bring all programs back, eventually filter by permissions
    @programs = Program.all
  end

  # GET /courses/1/edit
  def edit
    # Currently we'll bring all programs back, eventually filter by permissions
    @programs = Program.all

    @tracks = Track.all
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        # Currently we'll bring all programs back, eventually filter by permissions
        @programs = Program.all
        @tracks = Track.all
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        @programs = Program.all
        @tracks = Track.all
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.archived!

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private

    # User callbacks to share coommon setup or constraints between actions.
    def set_course
      @course = Course.find params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :number, :description, :program_ids, :track_id)
    end
end

app/views/courses/_form.html.haml
= bootstrap_form_for @course, label_errors: true, :html => { :class => 'form-horizontal' } do |f|
  = f.alert_message 'Please check the following errors.', error_summary: false
  = f.text_field :name
  = f.text_field :number
  = f.text_area :description, rows: 5
  = f.select :track_id, options_from_collection_for_select(@tracks, 'id', 'name')
  = f.select :program_ids, options_from_collection_for_select(@programs, 'id', 'name')
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")),
    courses_path, :class => 'btn btn-secondary'

app/views/courses/edit.html.haml
:ruby
  model_class = Course
  content_for :page_heading, 'Edit Course'

.row
  .col-sm-6
    .card
      .card-block
        = render :partial => "form"

app/views/courses/index.html.haml
:ruby
  model_class = Course
  content_for :title, 'Courses - Summer 2013'
  content_for :page_heading, model_class.model_name.human.pluralize

.container-fluid
  .row
    .col-sm-12
      .card.card-block
        .card-title
          %h4.pull-left Courses
          %h5.pull-right
            = link_to courses_path(format: :csv), title: 'Export Courses' do
              = fa_icon 'share-square-o'
            = link_to new_course_path, title: 'New Course' do
              = fa_icon 'plus'
        %table.table
          %thead
            %tr
              %th{ width: '15%' }= model_class.human_attribute_name(:name)
              %th{ width: '10%' }= model_class.human_attribute_name(:number)
              %th{ width: '35%' }= model_class.human_attribute_name(:description)
              %th{ width: '15%' }= model_class.human_attribute_name(:track)
              %th{ width: '15%' }= model_class.human_attribute_name(:created_at)
              %th{ width: '10%' }=t '.actions', :default => t("helpers.actions")
          %tbody
            - @courses.each do |course|
              - unless course.archived?
                %tr
                  %td= link_to course.name, course_path(course)
                  %td= course.number
                  %td= course.description
                  %td= course&.track&.name
                  %td= l course.created_at.to_date, format: :long
                  %td
                    = link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_course_path(course), :class => 'btn btn-sm btn-primary'
                    = link_to t('.destroy', :default => t("helpers.links.destroy")),
                      course_path(course), :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm",
                          :default => 'Are you sure?')) }, :class => 'btn btn-sm btn-danger'

app/views/courses/new.html.haml
:ruby
  model_class = Course
  content_for :page_heading, 'New Course'

.row
  .col-sm-6
    .card
      .card-block
        = render :partial => "form"

app/views/courses/show.html.haml
:ruby
  model_class = Course
  content_for :page_heading,  "Abundant Life Institute - #{@course.name}"

.container-fluid
  .row
    .col-sm-6
      .card.card-block
        .card-title
          %h5.pull-right
            = link_to course_path(id: @course.id, format: :csv), title: 'Export' do
              = fa_icon 'share-square-o'
            = link_to edit_course_path(@course), title: 'Edit' do
              = fa_icon 'pencil'
            = link_to(course_path(@course), method: 'delete',
              data: { confirm: t('.confirm')}, title: 'Delete') do
              = fa_icon 'trash'
        %dl
          %dt= model_class.human_attribute_name(:name)
          %dd= @course.name
          %dt= model_class.human_attribute_name(:number)
          %dd= @course.number
          %dt= model_class.human_attribute_name(:track)
          %dd= @course&.track&.name
          %dt= model_class.human_attribute_name(:description)
          %dd= @course.description
    .col-sm-6
      .card.card-block
        .card-title
          %h4.pull-left Assessments
          %h5.pull-right
            = link_to new_course_assessment_path(@course), title: 'New Assessment' do
              = fa_icon 'plus'
        %table.table.table-striped
          %thead
            %tr
              %th Assessment
              %th Type
              %th Total
          %tbody
            - @course.assessments.each do |assessment|
              %tr
                %td= link_to assessment.name, edit_course_assessment_path(@course.id, assessment.id)
                %td= assessment.assessment_type.name
                %td= assessment.potential